apiVersion: chaos-mesh.org/v1alpha1
kind: NetworkChaos
metadata:
  name: loss-paymentservice
  namespace: chaos-testing
spec:
  mode: all
  duration: 30s
  selector:
    namespaces:
      - default
    labelSelectors:
      app: paymentservice
  loss:
    loss: 0.1
