apiVersion: chaos-mesh.org/v1alpha1
kind: StressChaos
metadata:
  name: stress-cpu-adservice
  namespace: chaos-testing
spec:
  mode: all
  duration: 30s
  selector:
    namespaces:
      - default
    labelSelectors:
      app: adservice
  stressors:
    cpu:
      workers: 2
      load: 80
