# Copyright 2024 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: reviewservice-data
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: reviewservice
  labels:
    app: reviewservice
spec:
  selector:
    matchLabels:
      app: reviewservice
  template:
    metadata:
      labels:
        app: reviewservice
    spec:
      serviceAccountName: reviewservice
      securityContext:
        fsGroup: 1000
        runAsGroup: 1000
        runAsNonRoot: true
        runAsUser: 1000
      containers:
        - name: server
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - ALL
            privileged: false
            readOnlyRootFilesystem: true
          image: reviewservice
          ports:
          - containerPort: 8080
          readinessProbe:
            initialDelaySeconds: 10
            httpGet:
              path: "/_healthz"
              port: 8080
          livenessProbe:
            initialDelaySeconds: 10
            httpGet:
              path: "/_healthz"
              port: 8080
          env:
          - name: PORT
            value: "8080"
          - name: SQLITE_DB_PATH
            value: "/data/reviews.db"
          volumeMounts:
          - name: data
            mountPath: /data
          resources:
            requests:
              cpu: 100m
              memory: 64Mi
            limits:
              cpu: 200m
              memory: 128Mi
      volumes:
      - name: data
        persistentVolumeClaim:
          claimName: reviewservice-data
---
apiVersion: v1
kind: Service
metadata:
  name: reviewservice
  labels:
    app: reviewservice
spec:
  type: ClusterIP
  selector:
    app: reviewservice
  ports:
  - name: http
    port: 8080
    targetPort: 8080
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: reviewservice
